<?php

/**
 * Implements hook_enable(). 
 *
 * Prompt the site admin to rebuild the node_access table when 
 * this module is enabled.
 */
function domain_wf_enable() {
  node_access_needs_rebuild(TRUE);
}

/**
 * Implements hook_disable(). 
 *
 * Prompt the site admin to rebuild the node_access table when 
 * this module is disabled.
 */
function domain_wf_disable() {
  node_access_needs_rebuild(TRUE);
}
